---
# role: git
# file: molecule/dev/molecule.yml

dependency:
  name: "galaxy"
  options:
    role-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      allow_world_readable_tmpfiles: true
      callbacks_enabled: "ansible.posix.profile_tasks,ansible.posix.timer"
      callback_result_format: "yaml"
      remote_tmp: "/tmp/.ansible/tmp"
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
    prepare: "../resources/playbooks/prepare.yml"
  inventory:
    group_vars:
      all:
        git_user_config:
          - user: "git_molecule"
            name: "user.name"
            value: "Git Molecule"
          - user: "git_molecule"
            name: "user.email"
            value: "git-molecule@example.invalid"
          - user: "git_molecule"
            name: "init.defaultBranch"
            value: "main"
          - user: "git_molecule"
            name: "gpg.ssh.allowedSignersFile"
            value: "/home/git_molecule/.ssh/allowed_signers"
          - user: "git_molecule"
            name: "url.https://example.invalid/.insteadOf"
            value: "molecule:"
          - user: "git_molecule"
            name: "alias.obsolete"
            state: "absent"
          - user: "git_molecule_other"
            name: "user.name"
            value: "Other Git User"
          - user: "git_molecule_other"
            name: "user.email"
            value: "other@example.invalid"
        git_ssh_signing:
          - user: "git_molecule"
            key: "/home/git_molecule/.ssh/id_ed25519"
verifier:
  name: "ansible"
scenario:
  test_sequence:
    - "dependency"
    - "destroy"
    - "syntax"
    - "create"
    - "prepare"
    - "check"
    - "converge"
    - "idempotence"
    - "check"
    - "verify"
    - "destroy"
  name: "dev"
platforms:
  - name: "almalinux-latest-git"
    image: "docker.io/jomrr/molecule-almalinux:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "debian-latest-git"
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "fedora-latest-git"
    image: "docker.io/jomrr/molecule-fedora:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "opensuse-leap-latest-git"
    image: "docker.io/jomrr/molecule-opensuse-leap:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "opensuse-tumbleweed-latest-git"
    image: "docker.io/jomrr/molecule-opensuse-tumbleweed:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "ubuntu-latest-git"
    image: "docker.io/jomrr/molecule-ubuntu:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
